### PR TITLE
ruby-sdk

### PR DESCRIPTION
**Pull request by oshribin**

### CODE REVIEW

**Comment by avinoamr** [comment]
@oshribin Is this still relevant?

**Comment by alonbrody** [comment]
@avinoamr @oshribin Isn't that what will turn the Ruby SDK to fit to the new SDK?

**Comment by avinoamr** [comment]
@oshribin - you have several notes here that you didn't respond to since Mar. Please reply.

**Comment by oshribin** [comment]
@avinoamr This PR was initiated on December, it was relevant then. the sdk-reader was changed since then. i cant tell if it still relevant without get into the code again and test it. There is a task for updating the ruby-sdk assigned to Lior. He was referenced to this PR because it might be very close for what we need today.

**Pull request closed without merging**
